"""Tests for Layer 7: ContentFactory engine.

Covers:
- All 5 content formats generated by default
- Subset of formats when specific ones are requested
- Each format has non-empty content
- word_count is accurate
- seo_keywords are populated
- target_platform matches format
- Works with minimal input (basic ProjectSpec, ForgeOutput, PublishResult)
"""

from __future__ import annotations

import pytest

from letsbuild.content.engine import ContentFactory, _count_words
from letsbuild.models.architect_models import (
    ADR,
    ADRStatus,
    FeatureSpec,
    FileTreeNode,
    ProjectSpec,
    SandboxValidationCommand,
    SandboxValidationPlan,
)
from letsbuild.models.content_models import ContentFormat
from letsbuild.models.forge_models import CodeModule, ForgeOutput, ReviewVerdict, SwarmTopology
from letsbuild.models.publisher_models import (
    CommitEntry,
    CommitPhase,
    CommitPlan,
    PublishResult,
    RepoConfig,
)

# ------------------------------------------------------------------
# Fixtures
# ------------------------------------------------------------------

FAKE_REPO_URL = "https://github.com/testuser/my-fastapi-project"


@pytest.fixture
def sample_validation_plan() -> SandboxValidationPlan:
    """Minimal SandboxValidationPlan with 3 commands."""
    return SandboxValidationPlan(
        commands=[
            SandboxValidationCommand(command="pip install -e .", description="Install package"),
            SandboxValidationCommand(command="pytest tests/ -v", description="Run tests"),
            SandboxValidationCommand(command="ruff check .", description="Lint code"),
        ],
        base_image="letsbuild/sandbox:latest",
    )


@pytest.fixture
def sample_project_spec(sample_validation_plan: SandboxValidationPlan) -> ProjectSpec:
    """Minimal but valid ProjectSpec for content generation tests."""
    return ProjectSpec(
        project_name="MyFastAPI Project",
        one_liner="A high-performance REST API built with FastAPI and Pydantic.",
        tech_stack=["python", "fastapi", "pydantic", "postgresql"],
        file_tree=[
            FileTreeNode(path="src", is_directory=True, description="Source code"),
            FileTreeNode(path="src/main.py", is_directory=False, description="Entry point"),
            FileTreeNode(path="tests", is_directory=True),
            FileTreeNode(path="pyproject.toml", is_directory=False),
        ],
        feature_specs=[
            FeatureSpec(
                feature_name="REST API",
                description="Core REST API endpoints with authentication.",
                module_path="src/api.py",
                estimated_complexity=5,
                acceptance_criteria=["GET /health returns 200", "POST /items creates item"],
            ),
            FeatureSpec(
                feature_name="Database Layer",
                description="SQLAlchemy ORM with async support.",
                module_path="src/db.py",
                estimated_complexity=6,
                acceptance_criteria=["Connects to PostgreSQL", "CRUD operations work"],
            ),
        ],
        sandbox_validation_plan=sample_validation_plan,
        adr_list=[
            ADR(
                title="Use FastAPI for REST API",
                status=ADRStatus.ACCEPTED,
                context="Need high-performance async Python framework.",
                decision="We will use FastAPI with Pydantic v2.",
                consequences="Team learns FastAPI; gains async support.",
            )
        ],
        skill_name="fullstack",
        complexity_score=5.0,
        estimated_loc=800,
        seniority_target="mid",
    )


@pytest.fixture
def sample_forge_output() -> ForgeOutput:
    """ForgeOutput with passing tests and review verdict."""
    return ForgeOutput(
        code_modules=[
            CodeModule(
                module_path="src/main.py",
                content='"""Entry point."""\nfrom fastapi import FastAPI\napp = FastAPI()\n',
                language="python",
                loc=3,
            )
        ],
        test_results={"pytest": True, "ruff": True},
        review_verdict=ReviewVerdict.PASS,
        review_comments=["Clean and well-structured."],
        quality_score=85.0,
        total_tokens_used=5000,
        total_retries=0,
        topology_used=SwarmTopology.HIERARCHICAL,
    )


@pytest.fixture
def sample_publish_result() -> PublishResult:
    """Minimal PublishResult with a fake repo_url."""
    commit_plan = CommitPlan(
        commits=[
            CommitEntry(
                message="feat: initial scaffold",
                files=["pyproject.toml", "src/main.py"],
                phase=CommitPhase.SCAFFOLDING,
                timestamp_offset_hours=0.0,
            )
        ],
        total_commits=1,
        spread_days=3,
    )
    return PublishResult(
        repo_url=FAKE_REPO_URL,
        commit_shas=["abc123"],
        readme_url=f"{FAKE_REPO_URL}/blob/main/README.md",
        repo_config=RepoConfig(
            repo_name="my-fastapi-project",
            description="A high-performance REST API.",
            topics=["python", "fastapi"],
        ),
        commit_plan=commit_plan,
    )


# ------------------------------------------------------------------
# Tests: format selection
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_content_factory_generates_all_five_formats_by_default(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """ContentFactory with no explicit formats generates all 5 ContentFormat values."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    assert len(results) == len(ContentFormat)
    generated_formats = {r.format for r in results}
    assert generated_formats == set(ContentFormat)


@pytest.mark.asyncio
async def test_content_factory_generates_subset_when_formats_specified(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """ContentFactory generates only the requested subset of formats."""
    requested = [ContentFormat.BLOG_POST, ContentFormat.TWITTER_THREAD]
    factory = ContentFactory(formats=requested)
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    assert len(results) == 2
    generated_formats = {r.format for r in results}
    assert generated_formats == set(requested)


@pytest.mark.asyncio
async def test_content_factory_generates_single_format(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """ContentFactory can generate a single format."""
    factory = ContentFactory(formats=[ContentFormat.YOUTUBE_SCRIPT])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    assert len(results) == 1
    assert results[0].format == ContentFormat.YOUTUBE_SCRIPT


# ------------------------------------------------------------------
# Tests: non-empty content
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_all_formats_have_non_empty_content(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Every generated ContentOutput must have non-empty content."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.content.strip(), f"Content for {output.format} must not be empty"


@pytest.mark.asyncio
async def test_all_formats_have_non_empty_titles(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Every generated ContentOutput must have a non-empty title."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.title.strip(), f"Title for {output.format} must not be empty"


# ------------------------------------------------------------------
# Tests: word_count accuracy
# ------------------------------------------------------------------


def test_count_words_helper_basic() -> None:
    """_count_words splits on whitespace correctly."""
    assert _count_words("hello world") == 2
    assert _count_words("one two three four five") == 5
    assert _count_words("") == 0
    assert _count_words("single") == 1


@pytest.mark.asyncio
async def test_word_count_matches_actual_content(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """word_count on each ContentOutput must equal len(content.split())."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        expected = len(output.content.split())
        assert output.word_count == expected, (
            f"{output.format}: word_count={output.word_count}, actual={expected}"
        )


@pytest.mark.asyncio
async def test_word_count_is_positive(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """word_count must be a positive integer for all formats."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.word_count > 0, f"word_count for {output.format} must be positive"


# ------------------------------------------------------------------
# Tests: seo_keywords
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_seo_keywords_are_populated(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """seo_keywords must be a non-empty list for every ContentOutput."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.seo_keywords, f"seo_keywords for {output.format} must not be empty"
        assert isinstance(output.seo_keywords, list)


@pytest.mark.asyncio
async def test_seo_keywords_include_tech_stack_terms(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """seo_keywords should include terms from the project tech stack."""
    factory = ContentFactory(formats=[ContentFormat.BLOG_POST])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    keywords_lower = [k.lower() for k in results[0].seo_keywords]
    # At least one tech stack item should appear in keywords
    assert any(tech.lower() in keywords_lower for tech in sample_project_spec.tech_stack)


@pytest.mark.asyncio
async def test_seo_keywords_capped_at_twenty(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """seo_keywords must contain at most 20 items."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert len(output.seo_keywords) <= 20, f"{output.format}: seo_keywords exceeds 20 items"


# ------------------------------------------------------------------
# Tests: target_platform
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_target_platform_matches_format(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """target_platform must match the expected platform for each ContentFormat."""
    expected_platforms: dict[ContentFormat, str] = {
        ContentFormat.YOUTUBE_SCRIPT: "YouTube",
        ContentFormat.BLOG_POST: "Medium",
        ContentFormat.LINKEDIN_CAROUSEL: "LinkedIn",
        ContentFormat.TWITTER_THREAD: "Twitter",
        ContentFormat.PROJECT_WALKTHROUGH: "GitHub",
    }
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        expected = expected_platforms[output.format]
        assert output.target_platform == expected, (
            f"{output.format}: expected platform '{expected}', got '{output.target_platform}'"
        )


# ------------------------------------------------------------------
# Tests: content references project name
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_content_references_project_name(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Each ContentOutput's content or title should mention the project name."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    project_name = sample_project_spec.project_name
    for output in results:
        has_name = project_name in output.content or project_name in output.title
        assert has_name, (
            f"{output.format}: content/title must reference project name '{project_name}'"
        )


# ------------------------------------------------------------------
# Tests: ContentOutput model fields
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_content_output_has_content_id(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Each ContentOutput must have a non-empty content_id."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.content_id, f"{output.format}: content_id must be set"


@pytest.mark.asyncio
async def test_content_output_has_created_at(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Each ContentOutput must have a created_at timestamp."""
    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )

    for output in results:
        assert output.created_at is not None, f"{output.format}: created_at must be set"


# ------------------------------------------------------------------
# Tests: individual format generators
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_youtube_script_contains_hook_section(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """YouTube script must contain a HOOK section."""
    factory = ContentFactory(formats=[ContentFormat.YOUTUBE_SCRIPT])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )
    assert "HOOK" in results[0].content


@pytest.mark.asyncio
async def test_blog_post_has_introduction_section(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Blog post must contain an Introduction section."""
    factory = ContentFactory(formats=[ContentFormat.BLOG_POST])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )
    assert "Introduction" in results[0].content


@pytest.mark.asyncio
async def test_linkedin_carousel_has_multiple_slides(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """LinkedIn carousel must have at least 5 slides."""
    factory = ContentFactory(formats=[ContentFormat.LINKEDIN_CAROUSEL])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )
    slide_count = results[0].content.count("--- SLIDE")
    assert slide_count >= 5, f"Expected >=5 slides, got {slide_count}"


@pytest.mark.asyncio
async def test_twitter_thread_has_numbered_tweets(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Twitter thread must have at least 5 numbered tweets."""
    factory = ContentFactory(formats=[ContentFormat.TWITTER_THREAD])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )
    # Each tweet starts with "N/ "
    tweet_count = sum(
        1 for line in results[0].content.splitlines() if line[:3].rstrip("/ ").isdigit()
    )
    assert tweet_count >= 5, f"Expected >=5 tweets, got {tweet_count}"


@pytest.mark.asyncio
async def test_project_walkthrough_has_setup_section(
    sample_project_spec: ProjectSpec,
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """Project walkthrough must have a Setup & Installation section."""
    factory = ContentFactory(formats=[ContentFormat.PROJECT_WALKTHROUGH])
    results = await factory.generate(
        sample_project_spec, sample_forge_output, sample_publish_result
    )
    assert "Setup" in results[0].content or "Installation" in results[0].content


# ------------------------------------------------------------------
# Tests: minimal input (no ADRs, single feature)
# ------------------------------------------------------------------


@pytest.mark.asyncio
async def test_content_factory_with_minimal_project_spec(
    sample_forge_output: ForgeOutput,
    sample_publish_result: PublishResult,
) -> None:
    """ContentFactory handles a minimal ProjectSpec with no ADRs gracefully."""
    minimal_spec = ProjectSpec(
        project_name="Minimal Project",
        one_liner="A minimal test project.",
        tech_stack=["python"],
        file_tree=[FileTreeNode(path="src", is_directory=True)],
        feature_specs=[
            FeatureSpec(
                feature_name="Core",
                description="Core logic.",
                module_path="src/core.py",
                estimated_complexity=3,
            )
        ],
        sandbox_validation_plan=SandboxValidationPlan(
            commands=[
                SandboxValidationCommand(command="pip install -e .", description="Install"),
                SandboxValidationCommand(command="pytest tests/ -v", description="Test"),
                SandboxValidationCommand(command="ruff check .", description="Lint"),
            ],
            base_image="letsbuild/sandbox:latest",
        ),
        adr_list=[],
        skill_name="fullstack",
        complexity_score=3.0,
        estimated_loc=200,
        seniority_target="junior",
    )

    factory = ContentFactory()
    results = await factory.generate(minimal_spec, sample_forge_output, sample_publish_result)

    assert len(results) == len(ContentFormat)
    for output in results:
        assert output.content.strip(), f"{output.format}: content must not be empty"
        assert output.word_count > 0


@pytest.mark.asyncio
async def test_content_factory_with_zero_test_results(
    sample_project_spec: ProjectSpec,
    sample_publish_result: PublishResult,
) -> None:
    """ContentFactory handles ForgeOutput with empty test_results dict gracefully."""
    forge_output_no_tests = ForgeOutput(
        code_modules=[],
        test_results={},
        review_verdict=ReviewVerdict.PASS_WITH_SUGGESTIONS,
        review_comments=[],
        quality_score=70.0,
        total_tokens_used=1000,
        total_retries=0,
        topology_used=SwarmTopology.SEQUENTIAL,
    )

    factory = ContentFactory()
    results = await factory.generate(
        sample_project_spec, forge_output_no_tests, sample_publish_result
    )

    assert len(results) == len(ContentFormat)
    for output in results:
        assert output.content.strip()
