"""Jinja2 template-based README generator for Layer 6: GitHub Publisher."""

from __future__ import annotations

from typing import TYPE_CHECKING

import structlog
from jinja2 import Template

if TYPE_CHECKING:
    from letsbuild.models.architect_models import FileTreeNode, ProjectSpec
    from letsbuild.models.forge_models import ForgeOutput

__all__ = ["ReadmeGenerator"]

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Jinja2 README template (inline — no separate .j2 file)
# ---------------------------------------------------------------------------

_README_TEMPLATE = """\
# {{ project_name }}

> {{ one_liner }}

![Build](https://img.shields.io/badge/build-passing-brightgreen?style=flat-square)
![Python](https://img.shields.io/badge/python-3.12-blue?style=flat-square)
![License](https://img.shields.io/badge/license-MIT-green?style=flat-square)
![Code style](https://img.shields.io/badge/code%20style-ruff-black?style=flat-square)
![Quality](https://img.shields.io/badge/quality-{{ quality_score | int }}%25-{{ quality_badge_color }}?style=flat-square)

---

## Architecture

```mermaid
flowchart TD
{{ mermaid_diagram }}
```

---

## Features

{% for feature in features %}
- **{{ feature.feature_name }}** — {{ feature.description }}
{% if feature.acceptance_criteria %}
{% for criterion in feature.acceptance_criteria %}
  - {{ criterion }}
{% endfor %}
{% endif %}
{% endfor %}

---

## Quick Start

```bash
# Clone
git clone https://github.com/<your-username>/{{ repo_slug }}.git
cd {{ repo_slug }}

# Install dependencies
{{ install_command }}

# Run
{{ run_command }}
```

---

## Tech Stack

| Technology | Role |
|------------|------|
{% for tech in tech_stack %}
| `{{ tech }}` | — |
{% endfor %}

---

## Project Structure

```
{{ file_tree_display }}
```

---

## Architecture Decision Records

{% if adrs %}
| ID | Title | Status |
|----|-------|--------|
{% for adr in adrs %}
| {{ adr.adr_id[:8] }} | {{ adr.title }} | `{{ adr.status }}` |
{% endfor %}

> Full ADR documents live in [`docs/decisions/`](docs/decisions/).
{% else %}
_No ADRs recorded for this project._
{% endif %}

---

## Testing

```bash
{{ test_command }}
```

{% if test_summary %}
### Test Results

| Test | Result |
|------|--------|
{% for name, passed in test_results.items() %}
| `{{ name }}` | {{ "✅ pass" if passed else "❌ fail" }} |
{% endfor %}

**Tests passed:** {{ tests_passed }} / {{ tests_total }}
{% endif %}

---

## Contributing

1. Fork the repository
2. Create a feature branch: `git checkout -b feat/<description>`
3. Commit your changes using [Conventional Commits](https://www.conventionalcommits.org/)
4. Open a Pull Request

Please ensure `ruff check .` and all tests pass before submitting.

---

## License

MIT — see [LICENSE](LICENSE) for details.

---

*Generated by [LetsBuild](https://github.com/yashb98/LetsBuild) — Autonomous Portfolio Factory.*
"""


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------


def _slugify(name: str) -> str:
    """Convert a project name to a URL-safe slug."""
    return name.lower().replace(" ", "-").replace("_", "-")


def _quality_badge_color(score: float) -> str:
    """Return a shields.io colour based on quality score."""
    if score >= 90.0:
        return "brightgreen"
    if score >= 70.0:
        return "yellow"
    return "red"


def _build_mermaid(
    file_tree: list[FileTreeNode],
    feature_specs: list,  # list[FeatureSpec]
) -> str:
    """Produce a Mermaid flowchart body from feature specs (or file tree as fallback)."""
    lines: list[str] = []

    if feature_specs:
        # Use feature dependency graph when available
        node_ids: dict[str, str] = {}
        for i, feat in enumerate(feature_specs):
            node_id = f"F{i}"
            node_ids[feat.feature_name] = node_id
            lines.append(f'    {node_id}["{feat.feature_name}"]')

        for feat in feature_specs:
            src = node_ids[feat.feature_name]
            for dep_name in feat.dependencies:
                if dep_name in node_ids:
                    dep_id = node_ids[dep_name]
                    lines.append(f"    {dep_id} --> {src}")
    else:
        # Fallback: render top-level file-tree nodes as a linear chain
        top_dirs = [n for n in file_tree if n.is_directory][:6]
        for i, node in enumerate(top_dirs):
            label = node.path.strip("/")
            lines.append(f'    N{i}["{label}"]')
            if i > 0:
                lines.append(f"    N{i - 1} --> N{i}")

    return "\n".join(lines) if lines else '    A["Project"]'


def _render_file_tree(nodes: list[FileTreeNode], prefix: str = "") -> list[str]:
    """Recursively render a file tree in ASCII-art style."""
    lines: list[str] = []
    for i, node in enumerate(nodes):
        connector = "└── " if i == len(nodes) - 1 else "├── "
        name = node.path.split("/")[-1] or node.path
        suffix = "/" if node.is_directory else ""
        desc = f"  # {node.description}" if node.description else ""
        lines.append(f"{prefix}{connector}{name}{suffix}{desc}")
        if node.is_directory and node.children:
            extension = "    " if i == len(nodes) - 1 else "│   "
            lines.extend(_render_file_tree(node.children, prefix + extension))
    return lines


def _detect_install_command(tech_stack: list[str]) -> str:
    """Infer the install command from the project's tech stack."""
    stack_lower = {t.lower() for t in tech_stack}
    if any(t in stack_lower for t in ("next.js", "nextjs", "react", "node", "typescript")):
        return "npm install"
    if any(t in stack_lower for t in ("poetry",)):
        return "poetry install"
    # Default Python
    return 'pip install -e ".[dev]"'


def _detect_run_command(tech_stack: list[str]) -> str:
    """Infer a sensible run command from the project's tech stack."""
    stack_lower = {t.lower() for t in tech_stack}
    if any(t in stack_lower for t in ("next.js", "nextjs", "react")):
        return "npm run dev"
    if any(t in stack_lower for t in ("fastapi", "uvicorn")):
        return "uvicorn app.main:app --reload"
    if any(t in stack_lower for t in ("flask",)):
        return "flask run"
    if any(t in stack_lower for t in ("django",)):
        return "python manage.py runserver"
    return "python -m app"


def _detect_test_command(tech_stack: list[str]) -> str:
    """Infer a test command from the project's tech stack."""
    stack_lower = {t.lower() for t in tech_stack}
    if any(t in stack_lower for t in ("next.js", "nextjs", "react", "node", "typescript")):
        return "npm test"
    return "pytest tests/ -v --cov=. --cov-report=term-missing"


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------


class ReadmeGenerator:
    """Generates a professional README.md from a ProjectSpec and ForgeOutput.

    Uses an inline Jinja2 template to produce consistent, structured markdown
    suitable for portfolio GitHub repositories.
    """

    def __init__(self) -> None:
        self._template: Template = Template(_README_TEMPLATE)
        self._log = structlog.get_logger(self.__class__.__name__)

    def generate(self, project_spec: ProjectSpec, forge_output: ForgeOutput) -> str:
        """Render a full README markdown string.

        Args:
            project_spec: The project specification from Layer 4.
            forge_output: The code-forge output from Layer 5.

        Returns:
            Complete README.md content as a string.
        """
        self._log.info(
            "readme_generator.generating",
            project_name=project_spec.project_name,
            quality_score=forge_output.quality_score,
        )

        # Derive computed values
        test_results: dict[str, bool] = forge_output.test_results
        tests_passed = sum(1 for v in test_results.values() if v)
        tests_total = len(test_results)
        test_summary = tests_total > 0

        mermaid_body = _build_mermaid(project_spec.file_tree, project_spec.feature_specs)
        tree_lines = _render_file_tree(project_spec.file_tree)
        file_tree_display = project_spec.project_name + "/\n" + "\n".join(tree_lines)

        repo_slug = _slugify(project_spec.project_name)
        install_cmd = _detect_install_command(project_spec.tech_stack)
        run_cmd = _detect_run_command(project_spec.tech_stack)
        test_cmd = _detect_test_command(project_spec.tech_stack)

        context: dict[str, object] = {
            "project_name": project_spec.project_name,
            "one_liner": project_spec.one_liner,
            "quality_score": forge_output.quality_score,
            "quality_badge_color": _quality_badge_color(forge_output.quality_score),
            "mermaid_diagram": mermaid_body,
            "features": project_spec.feature_specs,
            "repo_slug": repo_slug,
            "install_command": install_cmd,
            "run_command": run_cmd,
            "tech_stack": project_spec.tech_stack,
            "file_tree_display": file_tree_display,
            "adrs": project_spec.adr_list,
            "test_command": test_cmd,
            "test_summary": test_summary,
            "test_results": test_results,
            "tests_passed": tests_passed,
            "tests_total": tests_total,
        }

        readme = self._template.render(**context)

        self._log.info(
            "readme_generator.done",
            project_name=project_spec.project_name,
            readme_chars=len(readme),
        )
        return readme
